stages:
  - lint
  - test
  - build
  - deploy

include:
  - component: $CI_SERVER_HOST/oksuf/pipeline-common/commitlint@~latest
    inputs:
      stage: lint
    rules:
      - if: $CI_MERGE_REQUEST_IID
  - component: $CI_SERVER_HOST/oksuf/pipeline-common/semrel@~latest
    inputs:
      release_stage: release

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

default:
  image: node:18-buster-slim
  before_script:
    - npm install

stages:
  - lint
  - test
  - build
  - release
  - deploy

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm run test
  interruptible: true

